### ISSUE TITLE
Middleware broken since Next.JS > 13.4.12

### ISSUE THREAD

**Issue by fritterhoff** [nibtime/next-safe-middleware#98]
Hi,

I'm aware that this project seems to be not maintained anymore but maybe somebody also struggled with issues since Next.JS version 13.4.13 and later.

Depending on the version I get slightly different issues. From my point of view all have common that loading the manifest seems to fail.

**Comment by Phoenix-Alpha** [comment]
@nibtime, sorry for pinging - is this project still maintained?

**Comment by fritterhoff** [comment]
Seems like not 👎🏼 I tried to upgrade and debug it on my own but that seems to be senseless.
